#!/usr/bin/env node
/**
 * Generates public/sitemap.xml -- every page this wiki actually has.
 *
 * The routes are static and the ids are not: a component page exists because
 * components_full.json has that component in it, so the only sitemap that
 * stays true is one generated from the same files the app reads. Hand-listing
 * 470 URLs would be wrong by the next patch.
 *
 * Three properties are load-bearing, for the same reason gen-data-manifest.mjs
 * has its own (CI regenerates this and fails on a diff):
 *
 *   - Output is deterministic. Sources are read in file order and every list
 *     is sorted, so the same data always produces the same bytes.
 *   - Output is NOT Prettier-formatted, and the file is in .prettierignore --
 *     `npm run format` would otherwise reflow it and break the check.
 *   - Only linked pages are listed. A sitemap is a claim that these are the
 *     wiki's pages; an address that renders but that nothing links to is an
 *     orphan, and saying otherwise is how a crawler's budget gets spent on
 *     pages no reader can reach.
 *
 * The origin comes from src/app/core/site.config.json, which is also what the
 * app's canonical links use. One copy, so the two cannot disagree -- which is
 * also why this script owns the Sitemap: line in public/robots.txt rather
 * than leaving a third hand-typed copy of the hostname there.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const read = (...p) => JSON.parse(readFileSync(join(root, ...p), 'utf8'));

const { origin } = read('src', 'app', 'core', 'site.config.json');
if (!/^https?:\/\/[^/]+$/.test(origin)) {
  throw new Error(
    `site.config.json: origin must be scheme + host with no trailing slash, got ${origin}`,
  );
}

const components = read('data', 'components_full.json');
const planets = read('data', 'planets.json');
const objectives = read('data', 'objectives.json');
const guides = read('data', 'guides.json');
const circuits = read('data', 'circuits.json');

/**
 * The sections, in the order the header's nav presents them. Listed by hand
 * rather than derived, so a section stays findable even in the window where it
 * holds nothing yet.
 */
const SECTIONS = ['/', '/components', '/circuits', '/planets', '/stations', '/missions', '/guides'];

/** Not sections, and not omitted: an imprint that no one can find is not one. */
const LEGAL = ['/imprint', '/privacy'];

const urls = [
  ...SECTIONS.map((loc) => ({ loc })),

  // in_build only. The components list is built from inBuild(), so the 51
  // parts that are not placeable are reachable by URL and linked from
  // nowhere -- see the note about orphans above.
  ...components
    .filter((c) => c.in_build)
    .map((c) => c.id)
    .sort()
    .map((id) => ({ loc: `/components/${id}` })),

  // Stations included: /planets/:id serves them too, which is why
  // /stations links every station to an address under /planets.
  ...planets
    .map((p) => p.id)
    .sort()
    .map((id) => ({ loc: `/planets/${id}` })),

  ...objectives
    .map((o) => o.id)
    .sort((a, b) => a - b)
    .map((id) => ({ loc: `/missions/${id}` })),

  // Guides and circuits are the only entries with a real lastmod: they are
  // written here, so the repo knows when. Everything else changes when the
  // game patches, which is not a date this build knows -- and an invented
  // lastmod is worse than none, since a crawler that learns the dates are
  // fiction stops reading them at all.
  ...guides
    .map((g) => ({ loc: `/guides/${g.id}`, lastmod: g.updated }))
    .sort((a, b) => (a.loc < b.loc ? -1 : a.loc > b.loc ? 1 : 0)),

  ...circuits
    .map((c) => ({ loc: `/circuits/${c.id}`, lastmod: c.updated }))
    .sort((a, b) => (a.loc < b.loc ? -1 : a.loc > b.loc ? 1 : 0)),

  ...LEGAL.map((loc) => ({ loc })),
];

// No <priority> and no <changefreq>: both are ignored by every major crawler,
// and a file full of numbers nobody reads is a file that looks maintained
// without being maintained.
const body = urls
  .map(({ loc, lastmod }) => {
    const date = lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : '';
    return `  <url>\n    <loc>${origin}${loc}</loc>${date}\n  </url>`;
  })
  .join('\n');

writeFileSync(
  join(root, 'public', 'sitemap.xml'),
  // No "--" in the comment below: XML forbids a double hyphen inside one, and
  // the file this writes has to parse as XML or a crawler drops it silently.
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/gen-sitemap.mjs. Do not edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`,
);

// robots.txt is hand-written apart from this one line, which names the file
// above at an absolute URL -- the spec allows nothing relative there. Rewritten
// in place so the prose and the policy stay editable by hand.
const ROBOTS = join(root, 'public', 'robots.txt');
const robots = readFileSync(ROBOTS, 'utf8');
const line = `Sitemap: ${origin}/sitemap.xml`;
if (!/^Sitemap: .*$/m.test(robots)) {
  throw new Error('robots.txt has no Sitemap: line for this script to keep up to date');
}
writeFileSync(ROBOTS, robots.replace(/^Sitemap: .*$/m, line));

console.log(`sitemap.xml: ${urls.length} urls`);
